# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('user', models.CharField(choices=[('GT', 'GT'), ('Ano', 'Ano')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
